
= MapStruct

== Overview
MapStruct is an annotation based java library with the goal of simplifying mapping logic.
The need for a model to model mapping is a common one, especially in integration code.
This need can spawn a myriad of methods of the following form:
------
ModelAObject modelBObjectToModelAObject(ModelBObject objectB);
------
or:
------
void mapModelAToModelB(ModelAObject objectA, ModelBObject objectB);
------
When facing a huge model, implementation of a method like this becomes tedious.
Whether the size is overstretched due to the underlying complexity of the business process or to a programmer not adhering to the single responsibility principle often makes little difference in these situations.

Furthermore, mapping logic is by it's nature repetitive.
It most often ends up being a sequence of null or empty checks with a setter call in the conditional body.
MapStruct aims to exploit this repetitive nature to provide a specialized code generator.

Through a small example I aim to show how to configure and use MapStruct.

The ultimate result is a generated implementation which will most likely resemble a manually written class.
In fact MapStruct reference guide states:
------
"The general philosophy of MapStruct is to generate code which looks as much as possible as if you had written it yourself from hand."
... (1)
------
It's worth prefering generating over typing.
It's faster.
It cuts a lot of boiler plate code.
It's more consistent.
Type errors are cought in compile time while most other errors in build time.

In my opinion the best part of this approach is that it exposes the more complex parts of the mapping logic.

== Setup
The entire example code can be found in https://github.com/vsostaric/map_struct.git.
It is a simple maven project.
For a gradle or ant setup see MapStruct documentation (1).
For it to work mapstruct-jdk8 dependency is needed as well as maven-compiler-plugin configuration.
Example of the plugin configuration.
------
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.7.0</version>
    <configuration>
        <source>1.8</source>
        <target>1.8</target>
        <annotationProcessorPaths>
            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </path>
            <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${org.mapstruct.version}</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
------
I added lombok dependency since I need it to generate setters and build methods for my code to work.
If you're not using lombok remove it from the configuration.

The mapstruct-processor will generate an implementation class in maven compile lifecycle.
The generated class will be in the same package as the interface or abstract class used to configure the implemented class.

== Model Used for Presentation
Using a simple Person/PersonDTO model we can show an example of MapStruct usage.
------
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Person {

    private String fullName;
    private String address;
    private LocalDate dateOfBirth;
    private Car car;
    private int numberOfVisits;
    private BigDecimal moneyOnHisMind;

}
------
------
import lombok.Data;

@Data
public class PersonDTO {

    private String firstName;
    private String lastName;
    private String residence;
    private String born;
    private Long timesVisited;
    private String money;
    private CarDTO carDTO;

}
------
== Creating the mapper
To create a mapper we need to annotate an interface or an abstract class with org.mapstruct.Mapper.
In the example I will use an interface.
Convention set in MapStruct documentation is to create a public static instance of the mapper in the interface using the Mappers factory.
------
@Mapper
public interface PersonMapper {

    PersonMapper INSTANCE = Mappers.getMapper(PersonMapper.class);

    @Mappings({
            ... Mapping annotations here
    })
    PersonDTO personToPersonDTO(Person person);

}
------
This way the mapper can be used as a static resource.
-----
PersonMapper.INSTANCE.personToPersonDTO(personObject)
-----
The mapper annotation has a componentModel property.
From (2), this property:
------
"Specifies the component model to which the generated mapper should adhere."
------
This is helpful to define how are we going to use the mapper in our code.

The default value is "default".
This means that there is no component model and that it's expected you will be retrieving the mapper as a static resource, as seen above.

A different way of doing this would be autowiring PersonMapper as a spring bean.
This is done by setting the componentModel to spring.
------
@Mapper(componentModel = "spring")
public interface PersonMapper {
    ...
}

@Autowired
private PersonMapper personMapper;
------
A third way of using the mapper is setting the component model to cdi which makes the mapper an application-scoped CDI bean.
Then it can be injected into a class using the @Inject annotation.
------
@Mapper(componentModel = "cdi")
...
@Inject
private PersonMapper personMapper;
------
In my example I stick to spring.
The important part is to see that the MapStruct can be added to any Java application, regardless of the framework.
As long as we have Maven, Gradle or Ant to run it's code generator.

=== Simple Case
In the most simple case when the field is mapped one-to-one the implementation is a single annotation.
------
@Mapping(source = "address", target = "residence", defaultValue = "unknown")
------
The address and residence are the same field with different names.
In the generated implementation this code will appear:
------
if (person.getAddress() != null) {
  personDTO.setResidence(person.getAddress());
}
else {
  personDTO.setResidence("unknown");
}
------
Unfortunately, this simple case is sometimes not enough.
Sometimes, mapped field differ in more than name, they may even be of different type.

=== Type conversion
When mapped fields are of different types it may not be possible to map them in a simple manner.
MapStruct will perform most implicit conversion.
It will accept casting of primitive types to wrappers and between primitive types and String.

In case of converting a larger type to a smaller one, for instance long to int, precision issues may arrise.

But what if we have a complex type field?
And if it's mapped to a third type, like in the example:
------
public class Person {
    ...
    private Car car;
}
public class PersonDTO {
    ...
    private CarDTO carDTO;

}
------
In cases like this, it is possible to write the implementation manually.
First a mapping annotation is needed, to generate a call of a method catToCarDTO:
------
@Mapping(source = "car", target = "carDTO")
------
And then implement a default method to do the actual mapping.
In this example:
------
default CarDTO carToCarDTO(Car car) {
    return car != null ? CarDTO.builder().modelOfCar(car.getCarModel()).build() : null;
}
------
The default method is required in this case since I'm using an interface.
Here convention must be followed and we have to make sure the method has the correct signature.

==== Number or Date to String
In case of converting an int, BigDecimal or another number type to String we can use numberFormat parameter of the Mapping annotation to define the format.
The format String has to be able to be read by java.text.DecimalFormat.
Example of this:
------
@Mapping(source = "moneyOnHisMind", target = "money", numberFormat = "#.##E0")
------
In case of Date to String transformation the dateFormat parameter can be used to specify the format String.
------
@Mapping(source = "dateOfBirth", target = "yearOfBirth", dateFormat = "yyyy dd MM")
------
Using this code generated will be:
------
if (person.getDateOfBirth() != null) {
  personDTO.setYearOfBirth(DateTimeFormatter.ofPattern("yyyy dd MM").format(person.getDateOfBirth()));
}
------
MapStruct supports org.yoda.time.* as well as java.sql.* or java.time.*

=== Expression
If the mapping logic can be expressed in a single line, expression can be a viable choice.
This is an example of mapping one field fullName to two fields firstName and lastName using expression.
------
@Mapping(target = "firstName", expression = "java(person.getFullName().split(\" \")[0])")
@Mapping(target = "lastName", expression = "java(person.getFullName().split(\" \")[1])")
------
The mapping generated result will be:
------
personDTO.setFirstName(person.getFullName().split(" ")[0]);
personDTO.setLastName(person.getFullName().split(" ")[1]);
------
There are obvious problems.
What if fullName is null or empty?
What if it's a single word?
This would require us to expand the expression to something like this:
------
(StringUtils.isNotEmpty(person.getFullName()) && person.getFullName().split(\" \").length > 1) ? person.getFullName().split(\" \")[0] : ""
------
Obviously, a single expression can grow too long and hard to maintain, so it should be used carefully.
MapStruct supports only java expressions at this point.
Note that the expression must be wrapped in java(/expression/).

=== More Complex Mapping
If mapping logic can't be fulfilled with naming the source and target, with automatic type casting or with an expression, then we will have to expand the mapper.
Essentially we will have to write the mapping logic ourselves.
Previously I've shown an example of mapping different typed fields by manually writing the mapping logic.
Here I will go through different ways of doing this and more.

One way is to use an @AfterMapping annotation.
------
@AfterMapping
default void doComplexMapping(Person person, @MappingTarget PersonDTO personDTO) {
    // do complex mapping
}
------
This way the method doComplexMapping is called after the generated code finishes.
The generated mapper will have a call to the function before the return statement.
------
....
doComplexMapping( person, personDTO );
return personDTO;
....
------
Annotation @BeforeMapping works in a similar way, calling the method after the instance is created.

Another way is to create another bean and autowire the Mapper, expand it's functionality and use that bean for mapping in the application.
------
@Service
public class PersonComplexMapper() {

    @Autowired
    private PersonMapper personMapper;

    public PersonDTO personToPersonDTO(Person person) {
        PersonDTO personDTO = personMapper.personToPersonDTO(person);
        // do complex mapping
        return personDTO;
    }
}
------
Of course, you can use a analogous form depending on how you use the mapper.

MapStruct also has an annotation @DecoratedWith which can be used for the same result.
From (1):
-----
@Mapper
@DecoratedWith(PersonMapperDecorator.class)
public interface PersonMapper {

    PersonMapper INSTANCE = Mappers.getMapper( PersonMapper.class );

    PersonDto personToPersonDto(Person person);

    AddressDto addressToAddressDto(Address address);
}
...
public abstract class PersonMapperDecorator implements PersonMapper {

    private final PersonMapper delegate;

    public PersonMapperDecorator(PersonMapper delegate) {
        this.delegate = delegate;
    }

    @Override
    public PersonDto personToPersonDto(Person person) {
        PersonDto dto = delegate.personToPersonDto( person );
        // do complex mapping
        return dto;
    }
}
-----
The good part of this is that most of the simple requests can be handled by MapStruct, but even better is that this approach will isolate the more complex logic in the mapping requirement.
This way we focus on the difficult parts of our mapping, the ones which usually involve some additional data fetch or transformation.

== Inverse Mapping

Creating an inverse mapper is done with a single annotation.
------
@InheritInverseConfiguration
Person personDTOToPerson(PersonDTO personDTO);
------
However, the generated inverse mapper will not include any complex mappings via expressions or manually implemented methods.
MapStruct can't assume that the manual logic is invertible.
If the inverse mapping logic requires the fields to be mapped, an approach similar in the previous section must be applied to the inverse mapping method.

== Constraints

One important constraint to keep in mind is that the generated method will have some prerequisites on the model.
It will need a no argument constructor and setter methods on mapped fields.

If you have no control on the model structure, at least on the model you're mapping to then you should be cautious on using MapStruct.

== Aspects of MapStruct not covered
Here I will just mention what I didn't include in the example.
Look the official MapStruct documentation (1) for additional information.

* Mapping with multiple source objects
* Shared and inherited configuration

== Conclusion
MapStruct can provide a simplification to an otherwise bulky and ugly piece of logic.
It's convention over configuration approach can cover most simple cases and provide us with an easy annotation based way to generate a mapper.
When a need for more complex logic arises the service can be expanded and allow us to add manually written logic.

== Documentation
* (1) http://mapstruct.org/documentation/stable/reference/html/
* (2) http://mapstruct.org/documentation/1.2/api/