
= MapStruct

This article aims to illustrate ways of using this technology.
The need to map one model to another is common in integration code.
It usually results in huge mapping logic which is hard to maintain.
MapStruct can be used to mitigate these issues.
It is based on convention over configuration approach.

== Setup
The entire example code can be found in -----.
It is a simple maven project.
For it to work mapstruct-jdk8 dependency is needed as well as maven-compiler-plugin configuration.
Example of the plugin configuration.
------
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.7.0</version>
    <configuration>
        <source>1.8</source>
        <target>1.8</target>
        <annotationProcessorPaths>
            <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </path>
            <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${org.mapstruct.version}</version>
            </path>
        </annotationProcessorPaths>
        <compilerArgs>
            <compilerArg>
                -Amapstruct.defaultComponentModel=spring
            </compilerArg>
        </compilerArgs>
    </configuration>
</plugin>
------
The mapstruct-processor will generate an implementation class in maven compile lifecycle.

== Model Used for Presentation
Using a simple Person/PersonDTO model we can show an example of MapStruct usage.
------
public class Person {
    private String fullName;
    private String address;
    private LocalDate dateOfBirth;
    private Car car;
}
------
------
public class PersonDTO {
    private String firstName;
    private String lastName;
    private String residence;
    private String yearOfBirth;
    private CarDTO carDTO;
}
------
== Creating the mapper
A convention of creating the mapper set in MapStruct documentation is to create a public static instance of the mapper in the interface.
------
@Mapper
public interface PersonMapper {

    PersonMapper INSTANCE = Mappers.getMapper(PersonMapper.class);

    @Mappings({
            ... Mapping annotations here
    })
    PersonDTO personToPersonDTO(Person person);

}
------
A different way of doing this would be autowiring Mappers as a bean.

== Using the mapper
With the mapper as in the previous section it can be used.
-----
PersonMapper.INSTANCE.personToPersonDTO(personObject)
-----

=== Simple Case
In the most simple case when the field is mapped one-to-one the implementation is fairly simple.
------
@Mapping(source = "address", target = "residence", defaultValue = "unknown")
------
The address and residence are the same field with different names.
This makes simple.

=== Expression

=== Date and BigDecimal to String

=== More Complex Mapping

=== Suggestion on use

== Conclusion

== Documentation
